// Code generated by hand — mock for LocationRepository interface.
// Used in unit tests only.
package mocks

import (
	"context"

	"github.com/khangpd15/producttrace-ai/apps/go-core-service/internal/modules/location/domain"
	"github.com/stretchr/testify/mock"
)

// MockLocationRepository là mock của repository.LocationRepository.
type MockLocationRepository struct {
	mock.Mock
}

func (m *MockLocationRepository) Create(ctx context.Context, loc *domain.Location) error {
	args := m.Called(ctx, loc)
	return args.Error(0)
}

func (m *MockLocationRepository) GetByID(ctx context.Context, id string) (*domain.Location, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.Location), args.Error(1)
}

func (m *MockLocationRepository) GetByCode(ctx context.Context, code string) (*domain.Location, error) {
	args := m.Called(ctx, code)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*domain.Location), args.Error(1)
}

func (m *MockLocationRepository) Update(ctx context.Context, loc *domain.Location) error {
	args := m.Called(ctx, loc)
	return args.Error(0)
}

func (m *MockLocationRepository) Delete(ctx context.Context, id string) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockLocationRepository) HardDelete(ctx context.Context, id string) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockLocationRepository) FindNearby(ctx context.Context, lat, lng float64, radiusMeters float64, limit int) ([]*domain.LocationWithDistance, error) {
	args := m.Called(ctx, lat, lng, radiusMeters, limit)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*domain.LocationWithDistance), args.Error(1)
}
